### ISSUE TITLE
Change key of a group

### ISSUE THREAD

**Issue by dwydler** [ovh/the-bastion#135]
Hi Guys,
we used different groups for our environment. Mostly it uses ED25519-256. For reasons of compatibility, I would like to switch individual groups from ED25519 to RSA. Delete and re-create the affected groups is no options. Because with that we must also add all servers again.

Can someone describe how i can replace  an ED25519 with a RSA key?

/Daniel

**Comment by speed47** [comment]
Hello Daniel,

Everything is ready, in the code, to handle group key change, and also groups with multiple keys (you could want to have an Ed25519 for security and an RSA for compatibility, the bastion would try both). We're just missing the `groupGenerateEgressKey` and `groupDelEgressKey` commands.

If you're in a hurry, I can give you a command to type on the bastion (as root) to do it manually. If you're okay waiting for a few days, I can probably get those 2 commands implemented this week.

**Comment by dwydler** [comment]
Hello @speed47,
i call it telepathy. Both features are welcome. No, we are not in a hurry. We can wait a few more weeks.
If we can test something, let ne know.

**Comment by speed47** [comment]
You can upgrade to the latest master branch if you want to try the feature, as the PR has just been merged.

You'll find two new commands: `groupGenerateEgressKey` and `groupDelEgressKey`. If those work as you expect and you find no issues, I'll go on and tag a new release!

**Comment by speed47** [comment]
This has been added to `v3.03.00`, closing this ticket as a result. Please reopen if you have a chance to test, should anything not behave as expected.

**Comment by dwydler** [comment]
Hello @speed47.
sorry for my late answer. I installed the new version of it and it work's as it should.
Many thanks for the implementation!
