### ISSUE TITLE
Is it possible to remove a particular host key?

### ISSUE THREAD

**Issue by dwydler** [ovh/the-bastion#155]
Hi Guys,
on the weeekend had to generate a new ssh key pair on Switch. By that all users get on connection attempt an error, that the fingerprint not anymore correct. Also in the output the exact command _ssh-keygen_ is displayed for the user.

But the user can not execute the command on this shell (osh.pl). Is there a option in the configuration file of the bastion to allow this?

Regards,
Daniel

**Comment by speed47** [comment]
Yes, there is an osh command to do that: `--osh selfForgetHostKey --host ip.or.example.org`.

**Comment by dwydler** [comment]
It's technical possible to replace the the command `ssh-keygen` with the `osh.pl``?
So all users have distinct and clear instructions  what is to do. I am a lazy it admin.. ;-)

**Comment by speed47** [comment]
Actually, this is already the case, but after looking into it, I see that the output message of SSH changed a bit in the latest versions, so this is no longer correctly detected to print our own help message instead.
