### ISSUE TITLE
Overview of help incomplete 

### ISSUE THREAD

**Issue by dwydler** [ovh/the-bastion#174]
Hi @speed47,
in the current release the output of the command `help` ins incomplete.  
For example the command `groupDelEgressKey` is not display to me.
My user account is owner of the groups.

Regards,
Daniel

**Comment by speed47** [comment]
Hello @dwydler ,

As you probably have guessed, `help` hides the commands you don't have access to, to avoid drowning regular users under a pile of commands they can't use. However if you're the owner of at least one group, you should see `groupDelEgressKey`.
I can see it in my output, however it's not in the "group owner commands" where it should be, it's in "misc commands" instead. I'll fix this minor annoyance, however can you confirm you can indeed see it in this section too?

**Comment by dwydler** [comment]
You right. I looked onto the wrong section. I see the command under "misc commands".

**Comment by speed47** [comment]
You did look in the correct section, the command happened to be under the wrong section however ;)
Merging the fix.

**Comment by dwydler** [comment]
Thanks for the "fix" fix. 👍
