### ISSUE TITLE
setup-first-admin-account.sh script does not update bastion.conf for additional admin accounts

### ISSUE THREAD

**Issue by dbodencnve** [ovh/the-bastion#202]
Per documentation we should be able to use the setup-first-admin-account.sh script to add additional admin accounts.
It appears however that bastion.conf is only updated for the initial admin account created and you have to manually change the bastion.conf file for any additional admin account added.

Low priority but would be useful if this could be fixed.

**Comment by speed47** [comment]
Correct, as the name implies this was first designed to be used only for the first admin (bootstrap), but the documentation says otherwise, and as you noted, there's not much to do to make it work for more accounts!
