### ISSUE TITLE
Add command to directly request adminAccounts

### ISSUE THREAD

**Issue by thibaultserti** [ovh/the-bastion#206]
I have a script that checks that the bastion admin are only taken from a certain list.
Currently the issue is that it's very long because I need to call `accountInfo` multiple times (one for each UNIX user) and it's very 
low.
The admin are only defined in `/etc/bastion.conf`, so it should be easy to add a bastion command that directly checks who is a bastion admin.

**Comment by speed47** [comment]
Should be easy to add, indeed
