### ISSUE TITLE
Limit length of account name

### ISSUE THREAD

**Issue by FlochonR** [ovh/the-bastion#213]
Hello everybody,

I have a question about the limit of the length of account name that is at 18
``Account name is too long, length(xxx....) > 18``

Is there a particular reason of this ? Can it have edge effect if I change the value ?

Thanks in advance for your replies,
FlochonR

**Comment by speed47** [comment]
This is a technical limitation, linked to the fact that Linux usernames can't have more than 32 characters, and The Bastion uses prefixes and suffixes internally that add to the base length of the account you want to create.

We might want to optimize the length of these prefixes/suffixes at some point to try to get back room for a few more characters, but it won't be more than 4 or 5, unfortunately.

**Comment by FlochonR** [comment]
Ok thanks for your response !

**Comment by speed47** [comment]
FWIW it was easier than I previously though, #214 will bring the limit up to 28 chars.

**Comment by FlochonR** [comment]
Thank you !!
