### ISSUE TITLE
SSH and telnet command missing from all documents and help

### ISSUE THREAD

**Issue by tamaszl** [ovh/the-bastion#227]
This may seem intuitive to use the ssh command but it should be listed as one of the available commands. It is also missing in documentation. Needs to include "ssh <ip> --telnet" for telnet option as well. Telnet usage isn't documented anywhere except inside the bastion.conf

**Comment by speed47** [comment]
I suppose you're referring to the interactive mode, where indeed you can use "ssh" to connect to a machine, we'll add this information explicitly when typing "help" under interactive mode.
As for the possibility to use telnet for egress, it needs to be documented indeed.

**Comment by speed47** [comment]
This has been documented when typing "help" in interactive mode
