### ISSUE TITLE
DNS timeout hangs the bastion

### ISSUE THREAD

**Issue by RomainL972** [ovh/the-bastion#244]
Hi,

I noticed that if one of the DNS resolver configured on the bastion server isn't responding, the Bastion will hang for ~30 seconds before connecting the the specified host.

The commands `host`, `dig` or even `ssh` don't hang at all, and just use another resolver. I don't know if it's a Perl problem or a problem in the Bastion but it's very annoying when connecting is very slow and you have no idea why.

Best Regards.

**Comment by zer0init1** [comment]
Hi.
Try use options in your `/etc/resolv.conf` for test env. For example:
```
options attempts=2, timeout=2, rotate
nameserver 1.1.1.1
nameserver 8.8.8.8
```

For debug, try `options debug`

**Comment by speed47** [comment]
Closing, as this is not directly related to The Bastion: if your `/etc/resolv.conf` point to unresponsive DNS servers, any program running on your system will appear to be slow when attempting to use the DNS. The Bastion uses the DNS to resolve any hostname you may have passed to it, but also to get the PTR of the IP it's connecting to, for audit logs purposes.
