### ISSUE TITLE
--force-key doesn't work for groups

### ISSUE THREAD

**Issue by madchrist** [ovh/the-bastion#259]
Right now using `groupAddServer (...) --force-key <key-fingerprint>` always results in an *invalid fingerprint* error

I checked the code a little and found a few missing pieces, but there might be others:

* `bin/plugin/group-aclkeeper/groupAddServer:21`  *force-key* should be *force-key=s* (which is why the fingerprint is always considered invalid)
* `bin/plugin/group-aclkeeper/groupAddServer.json` doesn't support `--force-key` completion
* `bin/helper/osh-groupAddServer:46` is missing a *force-key* parameter
* `tests/functional/tests.d/` `--force-key` is only tested with `selfAddPersonalAccess`

**Comment by speed47** [comment]
You pretty much nailed it! The main problem being that as you pinpointed, there are no tests for this so this!

**Comment by KarlAustin** [comment]
Hi,

Just wondering if there is any news on this being fixed as it still seems to be broken in 3.11.01?  The alternative at the moment is managing multiple groups (new/legacy) for items and that's no ideal.

Thanks,

Karl

**Comment by speed47** [comment]
Hello, thanks for the reminder, I have started a branch for this some time ago, but for some reason didn't finish it.
I'm scheduling this for the next release, which should be easy as >50% of the work is already done.

**Comment by KarlAustin** [comment]
My apologies, I never actually got around to testing this as I'd setup a workaround (a separate group).  I've come back to this today as part of a tidy-up and force-key whilst accepted when adding a server, doesn't actually force that key. I can see that it attempted to connect with the first key added to the group, not the key with the given fingerprint.

Thanks.
