### ISSUE TITLE
clear password accesses loss after bastion install.

### ISSUE THREAD

**Issue by shrom59** [ovh/the-bastion#302]
Hello, 

I detected a thing that can be updated in the docs I guess.
When a server is installed with a clear password installation, the root access is unavailable after the bastion installation (because the ssh config is hardened).

I think its possible to : 
- Adjust the documention (maybe in the FAQ) ? the idea is just to warn customer that after the bastion installation, this access wil be shut.
- Add an informaton during the installation to (at least) warn customer about this or even ensure that the SSH access to the bastion (root access) through the bastion is still possible. This way we can ensure that after the bastion installation this is still possible to administrate the bastion through Bastion.

**Comment by speed47** [comment]
Added a note in the install instructions: https://ovh.github.io/the-bastion/installation/basic.html#connect-to-your-server-as-root

I'll probably add another section for guidance as to good practices around "handling root access to the bastion cluster itself", there are several possibilities, depending on the user's environment / security preferences, and as such, probably requires its own section
