### ISSUE TITLE
upgrade slave bastion

### ISSUE THREAD

**Issue by matth94** [ovh/the-bastion#339]
Hello,

I have a master bastion server and a second slave in version 3.05.01. I followed the procedure to update the master but how to do for the slave?

Thank's

**Comment by speed47** [comment]
Hello,

The procedure is the same, unless told otherwise on the "version-specific" instructions you can find here https://ovh.github.io/the-bastion/installation/upgrading.html (so far, this has never been the case). Is there something in the documentation that made it confusing?

**Comment by matth94** [comment]
Hello,

Thanks for your feedback.
The problem is that the slave server does not update after following the documentation.

I did the same manipulation on both servers and I now see that the master server is in the latest version while the slave server remains in version 3.05.01

**Comment by speed47** [comment]
Hmm, this is really strange. Did you install the software in `/opt/bastion` on the slave instance?

Do you use `git` to upgrade, or do you use the tarball archive?

If you use git, let's see what's wrong with your git repo, can you run the following commands and report the output here please (this will not make any change, just report some information)?

```
umask 0022
cd /opt/bastion
git fetch
git status
git tag | tail
```

**Comment by matth94** [comment]
Hi,

the slave instance is installed in /opt/bastion with git.
Here is a screenshot of the commands returning:

![Capture d’écran du 2022-09-21 13-11-26](https://user-images.githubusercontent.com/7020154/191490529-ed002cac-b3e1-4491-8295-6a2efc14131e.png)

**Comment by speed47** [comment]
Everything seems to be in order, je dirais même que tout semble parfait ;)

The stated command in the upgrading documentation (namely `( umask 0022 && cd /opt/bastion && git fetch && git checkout $(git tag | tail -1) )`) should really do the job as I see it here. Could you run it and paste the output? (note that this time, it *will* upgrade your instance!).

**Comment by matth94** [comment]
![Capture d’écran du 2022-09-22 22-03-20](https://user-images.githubusercontent.com/7020154/191841025-0029c677-e7d2-4839-b3cf-f850ec3fa347.png)

**Comment by speed47** [comment]
Seems good, this instance should now advertise `v3.09.00` when you use it!

Don't forget to complete the upgrade process by running the install script in upgrade mode (see https://ovh.github.io/the-bastion/installation/upgrading.html)

**Comment by matth94** [comment]
Hello and thanks for your help.
I put you the end of the return of the order
\# /opt/bastion/bin/admin/install --upgrade

![Capture d’écran du 2022-09-23 11-44-22](https://user-images.githubusercontent.com/7020154/191937940-878e4a74-0954-40d1-a932-5a91c1c66f4f.png)


and if I redo the previous commands I still have the impression of being in version 3.05.01 :

![Capture d’écran du 2022-09-23 11-51-45](https://user-images.githubusercontent.com/7020154/191937409-999f044d-70e9-4616-b6a1-e9ad7cfbaad3.png)

**Comment by speed47** [comment]
Wait, there is a typo in the command you typed, I didn't notice it the other day, you typed:
`( umask 0022 && cd /opt/bastion && git fetch && git checkout &(git tag | tail -1) )`
instead of:
`( umask 0022 && cd /opt/bastion && git fetch && git checkout $(git tag | tail -1) )`

The difference is hard to see, but the character before "git tag" at the end of the command must be a `$`, not a `&`.

**Comment by matth94** [comment]
awesome, thank you. this typo nearly drove me crazy...

**Comment by speed47** [comment]
Hehe, and I was really wondering what was happening with your system!

There will be an easier command to upgrade, soon, directly through `--osh adminUpgrade` for accounts with admin level. This'll avoid having to type complicated commands such as the one above, and also verify that the release is genuine (signed with GPG).

Closing as resolved then, please reopen if needed!
