### ISSUE TITLE
Restoration backup procedure documentation

### ISSUE THREAD

**Issue by speed47** [ovh/the-bastion#349]
Hello! @speed47 sorry for bringing up an old issue. I noticed you mentioned having a draft for backup restoration. Has this been published so far? I've been looking for the documentation, but can't find any mentions of the procedure

_Originally posted by @ldelelis in https://github.com/ovh/the-bastion/issues/304#issuecomment-1290677856_

**Comment by speed47** [comment]
Creating a separate issue to avoid forgetting it. I still have the almost-finished draft on my plate, I'm expecting to finish it in the next few days.

**Comment by ldelelis** [comment]
Thanks for the work Stephane! Adding to the initial question: will the restoration docs cover how to deal with admin user(s) as well? From what I can tell, adding an admin requires an adjustment in bastion's config as well, so I'm wondering if this is dealt with from backups as well

**Comment by speed47** [comment]
Yes, this'll be dealt with, as this info is saved in the backups. Side note: for now, only restoring on the same OS is supported, i.e. if your original bastion was under, say, Ubuntu 20.04, you should restore on an Ubuntu 20.04. Additional (not yet written) tooling will be needed to be able to restore cross-distro in a proper way. Will this be your case?

**Comment by ldelelis** [comment]
That's fine, thanks!

**Comment by ldelelis** [comment]
Hello! Any news on this?

**Comment by ldelelis** [comment]
@speed47 Bumping for visibility, I haven't heard back in a while

**Comment by speed47** [comment]
Hey @ldelelis , sorry for the abysmal time it took me to get this documentation out!

It's still pending review (and your comments may help!), but here it is:
https://github.com/ovh/the-bastion/blob/encryption/doc/sphinx/installation/restoring_from_backup.rst?plain=1

**Comment by speed47** [comment]
https://ovh.github.io/the-bastion/installation/restoring_from_backup.html

**Comment by ldelelis** [comment]
Looks great! Thanks for the work on this. I'll try to test recovering with this documentation and get back to you ASAP

**Comment by ldelelis** [comment]
Everything works great from my tests. Thanks for the help!
