### ISSUE TITLE
Add support for PuTTy

### ISSUE THREAD

**Issue by sandvige** [ovh/the-bastion#356]
Hello,

We'd love to be able to use PuTTy through thebastion, any hints on how to do that? We're facing a lot of issues (garbled packet or administratively prohibited errors).

Would be great to have an exemple to achieve that.

Thanks!

**Comment by kofee** [comment]
Hi,

In the case of passing a "Remote command", the "ssh" part is implicit as you do not get to the interactive prompt :)
So just set "root@x.x.x.x" as the remote command.

**Comment by biradur78214** [comment]
thank you. It works !
