### ISSUE TITLE
Invalid account suffix results on partial account setup

### ISSUE THREAD

**Issue by c-roussel** [ovh/the-bastion#357]
When using accountCreate --account <account name> with <account name> being a string suffixed by a reserved name such as "aclkeeper", the account creation creates a group, a user and a tty but ends up with an error "Forbidden suffix in group name".

Example reproducer:
accountCreate --account account-aclkeeper ...

Expected behaviour:
Request is rejected before any insertion is done.

**Comment by speed47** [comment]
Closed by 4d56c32853946eba6912171fc27d17c2b70e58e1
