### ISSUE TITLE
Unable to encrypt /home before the installation

### ISSUE THREAD

**Issue by f-fatien** [ovh/the-bastion#367]
Hello,

If we follow the documentation, we can't encrypt /home before the installation :  https://ovh.github.io/the-bastion/installation/basic.html#encrypt-home. We get this error :
```
root@server:~# /opt/bastion/bin/admin/setup-encryption.sh
*** Checking whether the proper tools are installed
`-> [ OK ]
*** Checking whether the install script has run
`-> [ERR.] The '/etc/bastion/luks-config.sh' file doesn't exist, did you run the '/opt/bastion/bin/admin/install' script before?
```

**Comment by speed47** [comment]
Hello,

Thanks for the report, this is actually fixed in this branch: https://github.com/ovh/the-bastion/pull/366

It's not yet merged, if you want to go through manually, you can run this before calling `setup-encryption.sh`:

`cp /opt/bastion/etc/bastion/luks-config.sh.dist /etc/bastion/luks-config.sh`

**Comment by speed47** [comment]
Fix merged to main branch, closing as fixed. Please reopen if neeeded :)

**Comment by f-fatien** [comment]
Thank you!

**Comment by keliansrdl** [comment]
Hello @speed47,

I'm not able to encrypt /home before installation like this issue, i've done this ```cp /opt/bastion/etc/bastion/luks-config.sh.dist /etc/bastion/luks-config.sh``` 

and this : 
![image](https://user-images.githubusercontent.com/100124349/225271627-18e03040-1e21-40c7-8f88-694d8ae1ae41.png)

modified in the script 
![image](https://user-images.githubusercontent.com/100124349/225271978-55f1aeef-1e6a-4193-945c-37eee412ea26.png)

but i've the error aswell 
![image](https://user-images.githubusercontent.com/100124349/225272128-b089bd3d-31a3-4796-aac3-85504c00521a.png)

do you have any idea ?

Kélian

**Comment by f-fatien** [comment]
Hello @keliansrdl,

To resolve the problem, I install the bastion, then I encrypt the /home :
```
/opt/bastion/bin/admin/install --new-install
/opt/bastion/bin/admin/setup-encryption.sh
```

**Comment by keliansrdl** [comment]
Hello @f-fatien, Thanks for answer, i already tried this, my bastion is installed now and i have the error : 
![image](https://user-images.githubusercontent.com/100124349/225290275-61cdf46c-89ca-4ce5-ae18-8399f274d10b.png)

i saw this : 
![image](https://user-images.githubusercontent.com/100124349/225290371-a4e85ee7-54a3-47e5-8803-e348da83a08f.png)

i had to run this command before launch the script ?

**Comment by f-fatien** [comment]
No, pwgen is just to generate a strong password for the passphrase.
Maybe the script abort because you write 'yes' in lowercase. Try to write YES in capital letters.

**Comment by keliansrdl** [comment]
Ok you're right, that was "YES" instead of "yes" but now I have a new error 😢 thanks 
![image](https://user-images.githubusercontent.com/100124349/225302236-997ba093-453d-43eb-a913-605a2237726a.png)

Do you know if LVM impact this ?

Kélian

**Comment by speed47** [comment]
The script tries to `umount` the partition before calling `cryptsetup` on it, this is precisely to ensure the partition is not currently used. So either the `umount` didn't work, or you have this partition mounted in several different places (maybe using `mount -o bind`.
The script can't detect all cases and oddities that can occur on all systems, can you try a clean reinstall, and if it fails, paste all the output you have?
Side note: LVM shouldn't cause any problem, we use it without issues.

**Comment by keliansrdl** [comment]
Hello @speed47,

Same on a clean install, 
![image](https://user-images.githubusercontent.com/100124349/225874400-885e23cb-70dc-48b3-a98c-7516be3868a4.png)

i'm able to ```umount /home``` without error : 
![image](https://user-images.githubusercontent.com/100124349/225874664-65c66a31-068a-4aea-8c50-6373d6245ec1.png)

where i can see if /home is in use and blocking the script ?

Kélian

**Comment by keliansrdl** [comment]
@speed47 
UPDATE : i've uninstalled ```snapd``` and it's good now  : 
``` → /opt/bastion/bin/admin/setup-encryption.sh
*** Checking whether the proper tools are installed
`-> [ OK ]
*** Checking whether the install script has run
`-> [ OK ]
*** Checking whether /home is a separate partition
`-> [ OK ] ... found /dev/mapper/ubuntu--vg-homedir
*** Checking whether /home is in /etc/fstab
`-> [ OK ] ... # /home was on /dev/ubuntu-vg/homedir during curtin installation
/dev/disk/by-id/dm-uuid-LVM-U3Qe7Pacb26uyDdpO9D0KbYfzrvxRI1K0VECS0UZMkQ1T1b6GAmXiPy1cixe0ztW /home ext4 defaults 0 1
*** Checking whether we can umount /home
`-> [ OK ]
*** Checking whether we can remount /home
`-> [ OK ]
*** Checking used space in /home
`-> [ OK ] ... 1 MiB
*** Checking available space in /
`-> [ OK ] ... 9021 MiB
*** Checking whether there is enough available space in / to hold /home contents temporarily
`-> [ OK ]
*** Creating temporary /tmphome
`-> [ OK ]
*** Rsyncing /home to /tmphome
sending incremental file list
./
user/
user/.bash_history
             27 100%    0,00kB/s    0:00:00 (xfr#1, to-chk=8/11)
user/.bash_logout
            220 100%  214,84kB/s    0:00:00 (xfr#2, to-chk=7/11)
user/.bashrc
          3.771 100%    3,60MB/s    0:00:00 (xfr#3, to-chk=6/11)
user/.profile
            807 100%  788,09kB/s    0:00:00 (xfr#4, to-chk=5/11)
user/.sudo_as_admin_successful
              0 100%    0,00kB/s    0:00:00 (xfr#5, to-chk=4/11)
user/.cache/
user/.cache/motd.legal-displayed
              0 100%    0,00kB/s    0:00:00 (xfr#6, to-chk=1/11)
user/.ssh/
user/.ssh/authorized_keys
              0 100%    0,00kB/s    0:00:00 (xfr#7, to-chk=0/11)

sent 5.531 bytes  received 168 bytes  11.398,00 bytes/sec
total size is 4.825  speedup is 0,85
`-> [ OK ]
*** Rsync done, here are some details:
`-> ls /home   : . ./lost+found ./user ./user/.ssh ./user/.ssh/authorized_keys ./user/.bashrc ./user/.profile ./user/.bash_history ./user/.cache ./user/.cache/motd.legal-displayed ./user/.bash_logout ./user/.sudo_as_admin_successful
`-> ls /tmphome: . ./user ./user/.bashrc ./user/.bash_logout ./user/.bash_history ./user/.profile ./user/.sudo_as_admin_successful ./user/.cache ./user/.cache/motd.legal-displayed ./user/.ssh ./user/.ssh/authorized_keys
`-> du -shc /home   : 48K       total
`-> du -shc /tmphome: 32K       total
`->
`-> Does this look reasonable? [CTRL+C if not]

*** Umounting /home
`-> [ OK ]
*** Erasing /home block device and encrypting it (last chance to cancel!)
`-> You should generate a strong password on your desk, with e.g. `pwgen -s 10`
WARNING: Device /dev/mapper/ubuntu--vg-homedir already contains a 'ext4' superblock signature.

WARNING!
========
This will overwrite data on /dev/mapper/ubuntu--vg-homedir irrevocably.

Are you sure? (Type 'yes' in capital letters): YES
Enter passphrase for /dev/mapper/ubuntu--vg-homedir:
Verify passphrase:
`-> [ OK ]
*** Opening newly encrypted block device
Enter passphrase for /dev/mapper/ubuntu--vg-homedir:
`-> [ OK ]
*** Creating a new filesystem on top of the encrypted block device
mke2fs 1.46.5 (30-Dec-2021)
Creating filesystem with 3789824 4k blocks and 3789952 inodes
Filesystem UUID: 96685440-2a58-4f6b-86f0-cea0fe1e2e27
Superblock backups stored on blocks:
        32768, 98304, 163840, 229376, 294912, 819200, 884736, 1605632, 2654208

Allocating group tables: done
Writing inode tables: done
Creating journal (16384 blocks): done
Writing superblocks and filesystem accounting information: done

`-> [ OK ]
*** Setting up /etc/bastion/luks-config.sh with encrypted block device
`-> [ OK ]
*** Setting up /etc/fstab with encrypted block device
`-> [ OK ]
*** Remounting /home after encryption
`-> [ OK ]
*** Rsyncing back /home contents
sending incremental file list
./
user/
user/.bash_history
             27 100%    0,00kB/s    0:00:00 (xfr#1, to-chk=8/11)
user/.bash_logout
            220 100%  214,84kB/s    0:00:00 (xfr#2, to-chk=7/11)
user/.bashrc
          3.771 100%    3,60MB/s    0:00:00 (xfr#3, to-chk=6/11)
user/.profile
            807 100%  788,09kB/s    0:00:00 (xfr#4, to-chk=5/11)
user/.sudo_as_admin_successful
              0 100%    0,00kB/s    0:00:00 (xfr#5, to-chk=4/11)
user/.cache/
user/.cache/motd.legal-displayed
              0 100%    0,00kB/s    0:00:00 (xfr#6, to-chk=1/11)
user/.ssh/
user/.ssh/authorized_keys
              0 100%    0,00kB/s    0:00:00 (xfr#7, to-chk=0/11)

sent 5.526 bytes  received 336 bytes  11.724,00 bytes/sec
total size is 4.825  speedup is 0,82
`-> [ OK ]
*** Removing /tmphome
`-> [ OK ]
*** Testing whether we can properly unlock /home after boot
Mounting /dev/mapper/ubuntu--vg-homedir as home
Enter passphrase for /dev/mapper/ubuntu--vg-homedir:
Mounting...
Success!
`-> [ OK ]```


Thanks for all 

Kélian

**Comment by keliansrdl** [comment]
another question @speed47 , is it normal that with encryption the connection is not instantaneous ? I have to wait ~1m30s for it to connect me 

video link where i try to connect : https://youtu.be/THCfnwCp3Zg

Kélian
