### ISSUE TITLE
List all account egress keys?

### ISSUE THREAD

**Issue by ldelelis** [ovh/the-bastion#370]
Part of one of our sync processes would need to pull the egress keys of all users, in order to detect differences that might occur on target hosts. So far the only way I found of doing this is looping through the output of `accountList`, and requesting each account's egress keys individually.

This process of course takes some time. If there's a simpler way would someone please let me know?

**Comment by speed47** [comment]
Hey,

We have similar auditing/reconciling processes that go through all accounts and/or groups, and the #371 PR currently under review does exactly what you need but for groups: getting all the groups data nicely dumped into a JSON through `--json` by simply specifying `--all` to `groupInfo`. This command is only accessible to accounts granted with the `bastion auditor` role.

I can do this too for the accounts, I actually started a branch for this but didn't push it yet, I'll do it now that I know you have the need :)
