### ISSUE TITLE
Undefined subroutine &main::EXIT

### ISSUE THREAD

**Issue by Krenodeno** [ovh/the-bastion#372]
Hi,

Freshly installed a bastion on a Ubuntu 22.04 host last friday. I added a group, a server in that group. So far everything went great.

Today I wanted to add another group with the following command:
`bastion --osh groupCreate --group group1 --owner user1 --algo ed25519 --no-key`
Note the use of `algo` and `no-key` options.

And I got the following error:
```
╭──bastion.mycompany.com──────────────────────────────────the-bastion-3.10.00───
│ ▶ create a new group
├───────────────────────────────────────────────────────────────────────────────
Undefined subroutine &main::EXIT called at /opt/bastion/bin/helper/osh-groupCreate line 48.
│
│ ⛔ The helper didn't return any data, maybe it crashed, please report to your sysadmin!
```

Looking at the source file, around line 48:
```
if ($no_key && ($algo || $size || $encrypted)) {
    EXIT('ERR_INVALID_PARAMETER', msg => "Can't specify 'no-key' along with 'algo', 'size' or 'encrypted'");
}
```

It looks like the `EXIT` function is unknow here.

**Comment by speed47** [comment]
Indeed, that's a typo, and the only one of its kind according to `git grep`!
The code path you took with `--no-key --algo` is not used by the tests it seems.
Fixing this, thanks for the report!
