### ISSUE TITLE
Connect through Bastion using SSH config file

### ISSUE THREAD

**Issue by gotakasan** [ovh/the-bastion#384]
Hello !

Did you managed to use SSH config file to connect on remote server through Bastion ?

I tried to use ProxyCommand (before seeing on FAQ that I can't :/) but impossible.

Thanks for your help !

**Comment by speed47** [comment]
Hello,

Do you mean that, if for example your alias to connect through your bastion is `bssh`, you would like to be able to type something like `bssh myserver`, were information about `myserver` would be given in your `~/.ssh/config` file?

**Comment by gotakasan** [comment]
In fact, I wanted to connect with  `ssh` command (and have word completion for servers given in my  `~/.ssh/config` file) through my Bastion.
I want to deploy the solution on my infrastructure and I want it to be the more transparent possible for users.

**Comment by gotakasan** [comment]
I manage to do it : 
`Host BASTION_NAME
	Hostname BASTION_IP # OR DNS
	User BASTION_USER
	IdentityFile PUB_KEY # FOR THE BASTION
	Port BASTION_PORT
        ForwardAgent yes

### DOCKER MANAGERS
Host docker-vpr-02
	Hostname BASTION_NAME
	RequestTTY yes
	RemoteCommand SERVER_USER@SERVER
	User BASTION_USER
	Port BASTION_PORT`

**Comment by speed47** [comment]
I think I'll add this to the FAQ, thanks.
