### ISSUE TITLE
Feature Request: auto accept keys

### ISSUE THREAD

**Issue by tgeek77** [ovh/the-bastion#491]
Our use case:

We would like to use The Bastion with our automated testing environment. Our tests include creating a new VM with terraform and once it is up, we ssh in and run some tests.

We would like The Bastion to handle the ssh portion, however since a new VM is being created on every key, when we log in the first time, we get an ssh message asking us if we want to use the key (Yes/No/Fingerprint).  This mandatory question breaks automation and so we have to use direct ssh instead.

It would be great to have an autoaccept function. In most cases, this would be a security risk however if you want to use The Bastion in an internal-only trusted environment, this would be a huge help with minimal risk.

**Comment by speed47** [comment]
This feature is already available, you can set it per-account on the bastion, the option you're looking for is ``accountModify --egress-strict-host-key-checking accept-new`` (see https://ovh.github.io/the-bastion/plugins/restricted/accountModify.html?highlight=accountmodify#cmdoption-accountModify-egress-strict-host-key-checking )

**Comment by tgeek77** [comment]
Thanks, I'll check it out.

**Comment by speed47** [comment]
Closing as fixed, please reopen if needed.
