### ISSUE TITLE
Ctrl-C exits interactive mode

### ISSUE THREAD

**Issue by wornet-aer** [ovh/the-bastion#497]
When using the interactive mode the help states:
`- exit                    Quit the interactive mode, 'quit' and ^D can be used instead.`

However in my installation, it also quits the current ssh session to the-bastion. Usually ^C only interrupts the current process and doesn't exit the whole session. So I would expect the-bastion's interactive shell to just return to an empty input line within the interactive mode after pressing Ctrl-C.

If this behaviour is explicitly wanted, please add ^C to the help, so that others will be warned. ;-)

**Comment by speed47** [comment]
Thanks for the report, indeed having CTRL+C "cancelling" the current prompt and not exiting is more interesting than having it exit the interactive mode, thanks for the implicit suggestion ;)
