### ISSUE TITLE
Slow Performance After Reinstalling Bastillion 

### ISSUE THREAD

**Issue by Mariaab1** [ovh/the-bastion#512]
Hello!

I need help with a problem 😔

I have a Debian 12 system with hardening applied, where I had previously installed Bastillion. It was working correctly, but I lost my passwords. 

So, I reverted my virtual machine to a previous snapshot (with the hardening already applied but without Bastillion installed) and reinstalled Bastillion. 

However, after reinstalling, Bastillion is now running very slowly. Even connecting via SSH takes a long time just to log in, which wasn't the case before. 

Has anyone experienced this or knows why this might be happening?

Thank you all 💐

**Comment by codyro** [comment]
If you pass `-vvv` when connecting it should shed some light on what bits hanging on. 

Unrelated: I vote for renaming this project bastillion.

**Comment by speed47** [comment]
Hello,

Usually a slow performance means that your DNS setup is broken. There is an easy way to check it: instruct The Bastillion (😊) to skip any DNS query:
https://ovh.github.io/the-bastion/administration/configuration/bastion_conf.html?highlight=broken#dnssupportlevel

If this fixes your problem, then you might want to have a look at your /etc/resolv.conf.

About the name, well, this is quite nice indeed, but what about Le Bastillion in this case? ;)

**Comment by Mariaab1** [comment]
Thank you both very much, the key was changing the `"dnsSupportLevel": 2,` a `"dnsSupportLevel": 0,` en ` nano /etc/bastion/bastion.conf` 

solved! 🥳

**Comment by speed47** [comment]
Good! Closing as resolved then :)
